baseURL = "https://miruohotspring.net/"
languageCode = "ja"
title = "温泉"
theme = "mytheme"
disableKinds = ["categories", "terms"]

[params]
    herolink = "https://miruohotspring.net/"
    herolinktext = "TOP"
    favicon = "favicon.ico"

