baseURL = "https://miruohotspring.net/"
languageCode = "ja"
title = "みるを温泉"
theme = "mytheme"
disableKinds = ["categories", "terms"]

[params]
    herolink = "http://localhost:1313/"
    herolinktext = "TOP"
    favicon = "favicon.ico"

