baseURL = "https://miruohotspring.net/"
languageCode = "ja"
title = "温泉"
theme = "mytheme"
disableKinds = ["categories", "terms"]
summaryLength = 20
pygmentsCodefences = true
pygmentsUseClasses = true

[params]
    herolink = "https://miruohotspring.net/"
    herolinktext = "TOP"
    favicon = "favicon.ico"
    twitterID = "@miruohotspring"
    description = "温泉です"
    images = ["miruohotspring@1096.png"]

[taxonomies]
  tag = "tags"
